POST HTTP://localhost:8000/api/users/
Content-Type: application/json

{
    "email" : "teacher2@cusat",
    "username": "teacher2",
    "password": "abcxyz",
    "subjects": [
        {"title": "ACN", "subjectCode": "1604", "teacher": "teacher2"},
        {"title": "CN", "subjectCode": "1704", "teacher": "teacher2"},
        {"title": "OS", "subjectCode": "1502", "teacher": "teacher2"}
    ]
}